INSERT INTO content (title, slug, type, status, content, author, meta_description, tags, featured_image_path, event_date, event_time) VALUES
('Understanding Mental Health', 'understanding-mental-health', 'Resource', 'Published', 'This resource provides an overview of common mental health conditions, their symptoms, and available support.', 'Dr. P. Phiri', 'A comprehensive guide to understanding mental health and seeking support.', 'mental health, awareness, support', '1757315250956-1-intro-photo-final.jpg', NULL, NULL),
('Annual Wellness Conference 2025', 'annual-wellness-conference-2025', 'Event', 'Published', 'Join us for our annual conference focusing on holistic well-being, featuring expert speakers and interactive workshops.', 'BSPCP Admin', 'Annual conference on holistic well-being with expert speakers.', 'conference, wellness, event', '1757439752293-featured-image.jpg', '2025-10-26', '09:00:00'),
('New Partnership for Community Outreach', 'new-partnership-community-outreach', 'News', 'Published', 'We are excited to announce a new partnership aimed at expanding our community outreach programs.', 'Communications Team', 'Exciting new partnership to expand community outreach programs.', 'partnership, community, news', '1757270505514-sg2.png', NULL, NULL),
('Coping with Stress', 'coping-with-stress', 'Resource', 'Published', 'Practical strategies and techniques to manage and reduce stress in daily life.', 'Dr. L. Motsamai', 'Learn effective ways to cope with stress and improve your well-being.', 'stress, coping, mental health', '1757270639623-test.jpg', NULL, NULL),
('A Guide to Mindfulness', 'guide-to-mindfulness', 'Resource', 'Published', 'An introduction to mindfulness practices for improved focus, calm, and emotional regulation.', 'B. Kgosi', 'Discover the benefits of mindfulness and how to incorporate it into your routine.', 'mindfulness, meditation, well-being', '1757274664994-bspcp.jpg', NULL, NULL),
('Building Healthy Relationships', 'building-healthy-relationships', 'Resource', 'Published', 'Tips and advice for fostering strong, supportive, and healthy relationships with others.', 'S. Dube', 'Enhance your social connections with these essential relationship-building tips.', 'relationships, social, support', '1757315250956-1-intro-photo-final.jpg', NULL, NULL),
('Mental Health First Aid Workshop', 'mental-health-first-aid-workshop', 'Event', 'Published', 'A workshop to equip participants with skills to provide initial support to individuals experiencing mental health crises.', 'BSPCP Training', 'Gain vital skills in mental health first aid.', 'workshop, mental health, first aid', '1757439752293-featured-image.jpg', '2025-11-15', '10:00:00'),
('Charity Fun Run for Mental Wellness', 'charity-fun-run-mental-wellness', 'Event', 'Published', 'Join us for a fun run to raise awareness and funds for mental wellness initiatives.', 'Events Team', 'Run for a cause: supporting mental wellness in our community.', 'fun run, charity, mental wellness', '1757270505514-sg2.png', '2025-12-05', '07:30:00'),
('Webinar: The Importance of Sleep', 'webinar-importance-of-sleep', 'Event', 'Published', 'An online seminar discussing the critical role of sleep in mental and physical health.', 'Dr. K. Molefe', 'Understand why quality sleep is crucial for your overall health.', 'webinar, sleep, health', '1757270639623-test.jpg', '2025-11-22', '14:00:00'),
('BSPCP Launches New Youth Program', 'bspcp-launches-youth-program', 'News', 'Published', 'Exciting new program designed to support the mental well-being of young people across Botswana.', 'Youth Initiatives', 'New BSPCP program to empower youth mental health.', 'youth, program, news', '1757274664994-bspcp.jpg', NULL, NULL),
('Research Findings on Digital Wellbeing Published', 'research-digital-wellbeing-published', 'News', 'Published', 'Our latest research explores the impact of digital technology on mental well-being and offers recommendations.', 'Research Department', 'New research on digital well-being and its implications.', 'research, digital, well-being', '1757315250956-1-intro-photo-final.jpg', NULL, NULL),
('Volunteer Appreciation Day', 'volunteer-appreciation-day', 'News', 'Published', 'A special day dedicated to recognizing and celebrating the invaluable contributions of our volunteers.', 'Admin', 'Celebrating our dedicated volunteers and their impact.', 'volunteer, appreciation, news', '1757439752293-featured-image.jpg', NULL, NULL);
